server:
  port: "8080" # port to run the server on

oauth:
  client_id: "oMAJahYkvz3fIYQ1IMC71ASpvsbCOEI2" # linux.do client_id
  client_secret: "XIsCIx4ImTVxkgbuCnZHgPHDfi01NCap" # linux.do client_secret
  redirect_uri: "https://login.canterlot.me/" # linux.do redirect_uri
  token_url: "https://connect.linux.do/oauth2/token"
  auth_url: "https://connect.linux.do/oauth2/authorize"
  userinfo_url: "https://connect.linux.do/api/user"

google:
  client_id: "2159308334-qh1u7mtrhl2igoc13tltp7dq1413osjp.apps.googleusercontent.com" # google client_id
  client_secret: "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" # google client_secret
  refresh_token: "1//0497coH8Xm8EDCgYIARAAGAQSNgF-L9Irau6jfYoEJWgenpeXfxTtsfgpF39LElGunGNagPNWWSFzVuYC7V2PHZVxLMULGgIZPw" # google refresh_token
